### ISSUE TITLE
chore: update npm:@jsquash/avif

### ISSUE THREAD

**Issue by battall** [jamsinclair/jSquash#72]
its version is old, missing quality and other few EncodeOptions.

**Comment by jamsinclair** [comment]
Also we provide quality options. Did you possibly open this issue in the wrong project? 😅

**Comment by jamsinclair** [comment]
Thanks for the reminder @battall, I had been holding out on releasing the newer version due to some other breaking changes I wanted to make.

Rather than wait, let's just release the new changes! I've published [v2.0.0 to npm](https://www.npmjs.com/package/@jsquash/avif/v/2.0.0). Let me know if you have any issues!
